"""Initial database setup

Revision ID: f4099142ecd8
Revises: 
Create Date: 2025-04-27 09:47:04.589119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4099142ecd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('camera_name', sa.String(length=100), nullable=True),
    sa.Column('camera_type', sa.String(length=100), nullable=False),
    sa.Column('camera_brand', sa.String(length=100), nullable=True),
    sa.Column('recording_type', sa.String(length=100), nullable=True),
    sa.Column('coverage_description', sa.Text(), nullable=True),
    sa.Column('retention_period', sa.String(length=50), nullable=True),
    sa.Column('contact_preference', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('verified_on', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id_str', sa.String(length=20), nullable=False),
    sa.Column('location_address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reported_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_incident_id_str'), ['incident_id_str'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_incident_id_str'))

    op.drop_table('incident')
    op.drop_table('camera')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
